# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRWNN7MfaQFUsBNXGtBgd2oBbEJPmgNz
"""

import numpy as np

states = ['Low', 'Medium', 'High']
actions = ['Short', 'Medium', 'Long']

# Rewards (less waiting is better)
rewards = {
    'Low': 5,
    'Medium': 2,
    'High': -5
}

gamma = 0.9

# Simple transition (assumed)
def transition(state, action):
    if state == 'Low':
        return 'Low'
    elif state == 'Medium':
        return 'Low' if action == 'Long' else 'Medium'
    else:  # High traffic
        return 'Medium' if action == 'Long' else 'High'

def value_iteration():
    V = {s: 0 for s in states}

    while True:
        delta = 0
        new_V = V.copy()

        for s in states:
            values = []

            for a in actions:
                next_state = transition(s, a)
                values.append(rewards[next_state] + gamma * V[next_state])

            new_V[s] = max(values)
            delta = max(delta, abs(V[s] - new_V[s]))

        V = new_V

        if delta < 0.01:
            break

    return V

# RUN
V = value_iteration()

print("Value Iteration Results:")
for s in V:
    print(f"State: {s}, Value: {round(V[s],2)}")